import os
import datetime

class SummaryReporter:
    @staticmethod
    def generate_summary_markdown(results_data: list, output_dir: str):
        summary_dir = os.path.join(output_dir, "Summary")
        os.makedirs(summary_dir, exist_ok=True)

        total = len(results_data)
        passed = sum(1 for x in results_data if x["status"] == "PASSED")
        failed = sum(1 for x in results_data if x["status"] == "FAILED")
        skipped = sum(1 for x in results_data if x["status"] == "SKIPPED")
        pass_rate = (passed / total * 100) if total > 0 else 0

        passed_items = [x for x in results_data if x["status"] == "PASSED"]
        failed_items = [x for x in results_data if x["status"] == "FAILED"]

        passed_sample = "\n".join([f"✓ `{x['id']}` - {x['name']}" for x in passed_items[:15]])
        failed_sample = "\n".join([f"✗ `{x['id']}` - {x['name']}\n  *Reason: {x.get('reason', 'Assertion Failure')}*" for x in failed_items]) if failed_items else "None"

        md_content = f"""# 📱 Android Appium E2E Execution Summary

**Repository:** [Raviteja0271/Vital-Match](https://github.com/Raviteja0271/Vital-Match)  
**Build Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Target Application:** VitalMatch Android (`com.simats.vitalmatch`)  
**Platform:** Android (UiAutomator2)  
**🌐 Live GitHub Pages Report:** [View Latest Execution Report](https://raviteja0271.github.io/Vital-Match/reports/latest/execution-report.html)

---

### 📊 Execution Metrics

| Metric | Count / Percentage |
|---|---|
| **Total Test Cases** | **{total}** |
| **Executed** | **{total}** |
| **Passed** | **{passed}** |
| **Failed** | **{failed}** |
| **Skipped** | **{skipped}** |
| **Pass Percentage** | **{pass_rate:.1f}%** |

---

### ✅ PASSED TESTS (Sample)
{passed_sample}
... and {max(0, len(passed_items) - 15)} more passed tests.

---

### ❌ FAILED TESTS
{failed_sample}

---

*Report automatically generated by VitalMatch Enterprise Appium CI/CD Framework.*
"""

        filepath = os.path.join(summary_dir, "summary.md")
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(md_content)

        print(f"Markdown Summary generated at: {filepath}")
