package com.simats.vitalmatch.ui.theme

object AppStrings {
    private val translations = mapOf(
        "English" to mapOf(
            "home" to "Home",
            "emergencies" to "Emergencies",
            "donors" to "Donors",
            "search" to "Search",
            "my_requests" to "My Requests",
            "settings" to "Settings",
            "profile" to "Profile",
            "notifications" to "Notifications",
            "reports" to "Reports",
            "search_donors" to "Search Donors",
            "post_emergency" to "Post Emergency",
            "become_donor" to "Become Donor",
            "live_emergencies" to "Live Emergency Requests",
            "view_all" to "View All",
            "welcome" to "Welcome to VitalMatch",
            "app_theme" to "App Theme",
            "display_language" to "Display Language",
            "light_mode" to "Light Mode",
            "dark_mode" to "Dark Mode",
            "system_default" to "System",
            "back" to "Back",
            "call" to "Call",
            "sms" to "SMS",
            "logout" to "Log Out",
            "patient_name" to "Patient Name",
            "blood_type" to "Blood Group Needed",
            "hospital_name" to "Hospital Name",
            "contact_number" to "Contact Number",
            "save_changes" to "Save Changes",
            "full_name" to "Full Name",
            "mobile_number" to "Mobile Number",
            "last_donation_date" to "Last Donation Date",
            "state" to "State",
            "district" to "District",
            "city" to "Town/City",
            "register_now" to "Register Now",
            "request_help" to "Request urgent blood help",
            "emergency_feed_sub" to "Real-time blood requests near you",
            "find_donors_sub" to "Find blood donors near you",
            "additional_notes" to "Additional Notes",
            "all" to "All",
            "active" to "Active",
            "connected" to "Connected",
            "pending" to "Pending",
            "available" to "Available",
            "unavailable" to "Unavailable",
            "select_blood_group" to "Select blood group",
            "select_state" to "Select state",
            "select_district" to "Select district",
            "select_city" to "Select town/city",
            "send_request" to "Send Blood Request",
            "last_donation" to "Last donation",
            "post_emergency_submit" to "Post Emergency & Notify Donors",
            "notification_prefs" to "Notification Preferences",
            "emergency_alerts" to "Emergency Alerts",
            "eligibility_reminders" to "Eligibility Reminders",
            "newsletter" to "Newsletter & Tips",
            "account_security" to "Account & Security",
            "reset_password" to "Reset / Change Password"
        ),
        "Hindi (हिंदी)" to mapOf(
            "home" to "होम",
            "emergencies" to "आपात स्थिति",
            "donors" to "रक्तदाता",
            "search" to "खोजें",
            "my_requests" to "मेरी अनुरोध",
            "settings" to "सेटिंग्स",
            "profile" to "प्रोफाइल",
            "notifications" to "सूचनाएं",
            "reports" to "रिपोर्ट",
            "search_donors" to "दाता खोजें",
            "post_emergency" to "आपात स्थिति दर्ज करें",
            "become_donor" to "दाता बनें",
            "live_emergencies" to "लाइव आपातकालीन अनुरोध",
            "view_all" to "सभी देखें",
            "welcome" to "वाइटलमैच में आपका स्वागत है",
            "app_theme" to "ऐप थीम",
            "display_language" to "प्रदर्शन भाषा",
            "light_mode" to "लाइट मोड",
            "dark_mode" to "डार्क मोड",
            "system_default" to "सिस्टम",
            "back" to "पीछे",
            "call" to "कॉल करें",
            "sms" to "एसएमएस",
            "logout" to "लॉगआउट",
            "patient_name" to "मरीज का नाम",
            "blood_type" to "आवश्यक रक्त समूह",
            "hospital_name" to "अस्पताल का नाम",
            "contact_number" to "संपर्क नंबर",
            "save_changes" to "बदलाव सहेजें",
            "full_name" to "पूरा नाम",
            "mobile_number" to "मोबाइल नंबर",
            "last_donation_date" to "अंतिम रक्तदान तिथि",
            "state" to "राज्य",
            "district" to "जिला",
            "city" to "शहर",
            "register_now" to "अभी पंजीकरण करें",
            "request_help" to "तत्काल रक्त सहायता का अनुरोध करें",
            "emergency_feed_sub" to "आपके पास लाइव आपातकालीन अनुरोध",
            "find_donors_sub" to "अपने आस-पास रक्तदाता खोजें",
            "additional_notes" to "अतिरिक्त विवरण",
            "all" to "सभी",
            "active" to "सक्रिय",
            "connected" to "जुड़े हुए",
            "pending" to "लंबित",
            "available" to "उपलब्ध",
            "unavailable" to "अनुपलब्ध",
            "select_blood_group" to "रक्त समूह चुनें",
            "select_state" to "राज्य चुनें",
            "select_district" to "जिला चुनें",
            "select_city" to "शहर चुनें",
            "send_request" to "रक्त अनुरोध भेजें",
            "last_donation" to "अंतिम रक्तदान",
            "post_emergency_submit" to "आपात स्थिति दर्ज करें और दाताओं को सूचित करें",
            "notification_prefs" to "सूचना प्राथमिकताएं",
            "emergency_alerts" to "आपातकालीन अलर्ट",
            "eligibility_reminders" to "पात्रता अनुस्मारक",
            "newsletter" to "न्यूजलेटर और टिप्स",
            "account_security" to "खाता और सुरक्षा",
            "reset_password" to "पासवर्ड रीसेट करें"
        ),
        "Telugu (తెలుగు)" to mapOf(
            "home" to "హోమ్",
            "emergencies" to "అత్యవసరాలు",
            "donors" to "రక్తదాతలు",
            "search" to "వెతకండి",
            "my_requests" to "నా అభ్యర్థనలు",
            "settings" to "సెట్టింగ్స్",
            "profile" to "ప్రొఫైల్",
            "notifications" to "నోటిఫికేషన్లు",
            "reports" to "నివేదికలు",
            "search_donors" to "రక్తదాతలను వెతకండి",
            "post_emergency" to "అత్యవసర అభ్యర్థన",
            "become_donor" to "రక్తదాతగా మారండి",
            "live_emergencies" to "ప్రత్యక్ష అత్యవసర అభ్యర్థనలు",
            "view_all" to "అన్నీ చూడండి",
            "welcome" to "వైటల్ మ్యాచ్‌కి స్వాగతం",
            "app_theme" to "యాప్ థీమ్",
            "display_language" to "భాష",
            "light_mode" to "లైట్ మోడ్",
            "dark_mode" to "డార్క్ మోడ్",
            "system_default" to "సిస్టమ్",
            "back" to "వెనుకకు",
            "call" to "కాల్ చేయండి",
            "sms" to "ఎస్ఎంఎస్",
            "logout" to "లాగ్ అవుట్",
            "patient_name" to "రోగి పేరు",
            "blood_type" to "కావలసిన రక్తం గ్రూప్",
            "hospital_name" to "ఆసుపత్రి పేరు",
            "contact_number" to "సంప్రదించాల్సిన నంబర్",
            "save_changes" to "సేవ్ చేయండి",
            "full_name" to "పూర్తి పేరు",
            "mobile_number" to "మొబైల్ నంబర్",
            "last_donation_date" to "చివరి రక్తదాన తేదీ",
            "state" to "రాష్ట్రం",
            "district" to "జిల్లా",
            "city" to "పట్టణం/నగరం",
            "register_now" to "ఇప్పుడు నమోదు చేయండి",
            "request_help" to "రక్తం కోసం అత్యవసర అభ్యర్థన",
            "emergency_feed_sub" to "మీ దగ్గరలోని ప్రత్యక్ష రక్తం అభ్యర్థనలు",
            "find_donors_sub" to "మీ సమీపంలో ఉన్న రక్తదాతలను కనుగొనండి",
            "additional_notes" to "అదనపు వివరాలు",
            "all" to "అన్నీ",
            "active" to "సక్రియం",
            "connected" to "కలిసి ఉన్నారు",
            "pending" to "పెండింగ్",
            "available" to "అందుబాటులో ఉన్నారు",
            "unavailable" to "అందుబాటులో లేరు",
            "select_blood_group" to "రక్తం గ్రూప్‌ను ఎంచుకోండి",
            "select_state" to "రాష్ట్రాన్ని ఎంచుకోండి",
            "select_district" to "జిల్లాను ఎంచుకోండి",
            "select_city" to "నగరాన్ని ఎంచుకోండి",
            "send_request" to "రక్తం అభ్యర్థన పంపండి",
            "last_donation" to "చివరి రక్తదానం",
            "post_emergency_submit" to "అత్యవసర అభ్యర్థన నమోదు చేసి దాతలకు తెలపండి",
            "notification_prefs" to "నోటిఫికేషన్ ప్రాధాన్యతలు",
            "emergency_alerts" to "అత్యవసర హెచ్చరికలు",
            "eligibility_reminders" to "అర్హత జ్ఞాపికలు",
            "newsletter" to "వార్తాపత్రిక & సలహాలు",
            "account_security" to "ఖాతా & భద్రత",
            "reset_password" to "పాస్‌వర్డ్ మార్చండి"
        ),
        "Tamil (தமிழ்)" to mapOf(
            "home" to "முகப்பு",
            "emergencies" to "அவசரங்கள்",
            "donors" to "கொடையாளர்கள்",
            "search" to "தேடு",
            "my_requests" to "என் கோரிக்கைகள்",
            "settings" to "அமைப்புகள்",
            "profile" to "சுயவிவரம்",
            "notifications" to "அறிவிப்புகள்",
            "reports" to "அறிக்கைகள்",
            "search_donors" to "கொடையாளர்களைத் தேடு",
            "post_emergency" to "அவசர கோரிக்கை",
            "become_donor" to "கொடையாளராகு",
            "live_emergencies" to "நேரலை அவசர கோரிக்கைகள்",
            "view_all" to "அனைத்தையும் காண்",
            "welcome" to "VitalMatch-க்கு வரவேற்கிறோம்",
            "app_theme" to "செயலி தீம்",
            "display_language" to "மொழி",
            "light_mode" to "லைட் மோட்",
            "dark_mode" to "டார்க் மோட்",
            "system_default" to "சிஸ்டம்",
            "back" to "பின்செல்",
            "call" to "அழைக்க",
            "sms" to "எஸ்எம்எஸ்",
            "logout" to "வெளியேறு",
            "patient_name" to "நோயாளி பெயர்",
            "blood_type" to "தேவையான இரத்த வகை",
            "hospital_name" to "மருத்துவமனை பெயர்",
            "contact_number" to "தொடர்பு எண்",
            "save_changes" to "சேமி",
            "full_name" to "முழு பெயர்",
            "mobile_number" to "கைபேசி எண்",
            "last_donation_date" to "கடைசி இரத்த தான தேதி",
            "state" to "மாநிலம்",
            "district" to "மாவட்டம்",
            "city" to "நகரம்",
            "register_now" to "இப்போது பதிவு செய்",
            "request_help" to "அவசர இரத்த உதவி கோரிக்கை",
            "emergency_feed_sub" to "உங்களுக்கு அருகிலுள்ள நேரலை அவசர கோரிக்கைகள்",
            "find_donors_sub" to "உங்களுக்கு அருகிலுள்ள இரத்தக் கொடையாளர்களைக் கண்டறியவும்",
            "additional_notes" to "கூடுதல் விவரங்கள்",
            "all" to "அனைத்தும்",
            "active" to "செயலில்",
            "connected" to "இணைக்கப்பட்டது",
            "pending" to "நிலுவையில்",
            "available" to "கிடைக்கும்",
            "unavailable" to "கிடைக்காது",
            "select_blood_group" to "இரத்த வகையைத் தேர்ந்தெடு",
            "select_state" to "மாநிலத்தைத் தேர்ந்தெடு",
            "select_district" to "மாவட்டத்தைத் தேர்ந்தெடு",
            "select_city" to "நகரத்தைத் தேர்ந்தெடு",
            "send_request" to "இரத்த கோரிக்கை அனுப்பு",
            "last_donation" to "கடைசி தானம்",
            "post_emergency_submit" to "அவசர கோரிக்கையிட்டு கொடையாளர்களுக்கு அறிவி",
            "notification_prefs" to "அறிவிப்பு விருப்பங்கள்",
            "emergency_alerts" to "அவசர எச்சரிக்கைகள்",
            "eligibility_reminders" to "தகுதி நினைவூட்டல்கள்",
            "newsletter" to "செய்திமடல் & குறிப்புகள்",
            "account_security" to "கணக்கு & பாதுகாப்பு",
            "reset_password" to "கடவுச்சொல் மாற்று"
        ),
        "Kannada (ಕನ್ನಡ)" to mapOf(
            "home" to "ಮುಖಪುಟ",
            "emergencies" to "ತುರ್ತುಗಳು",
            "donors" to "ದಾನಿಗಳು",
            "search" to "ಹುಡುಕಿ",
            "my_requests" to "ನನ್ನ ವಿನಂತಿಗಳು",
            "settings" to "ಸಂಯೋಜನೆಗಳು",
            "profile" to "ಪ್ರೊಫೈಲ್",
            "notifications" to "ಸೂಚನೆಗಳು",
            "reports" to "ವರದಿಗಳು",
            "search_donors" to "ದಾನಿಗಳನ್ನು ಹುಡುಕಿ",
            "post_emergency" to "ತುರ್ತು ವಿನಂತಿ ಸಲ್ಲಿಸಿ",
            "become_donor" to "ದಾನಿಯಾಗಿರಿ",
            "live_emergencies" to "ಸಕ್ರಿಯ ತುರ್ತು ವಿನಂತಿಗಳು",
            "view_all" to "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
            "welcome" to "VitalMatch ಗೆ ಸ್ವಾಗತ",
            "app_theme" to "ಅಪ್ಲಿಕೇಶನ್ ಥೀಮ್",
            "display_language" to "ಭಾಷೆ",
            "light_mode" to "ಲೈಟ್ ಮೋಡ್",
            "dark_mode" to "ಡಾರ್ಕ್ ಮೋಡ್",
            "system_default" to "ಸಿಸ್ಟಮ್",
            "back" to "ಹಿಂತಿರುಗಿ",
            "call" to "ಕರೆ ಮಾಡಿ",
            "sms" to "ಎಸ್‌ಎಮ್‌ಎಸ್",
            "logout" to "ನಿರ್ಗಮಿಸಿ",
            "patient_name" to "ರೋಗಿಯ ಹೆಸರು",
            "blood_type" to "ಅಗತ್ಯವಿರುವ ರಕ್ತದ ಗುಂಪು",
            "hospital_name" to "ಆಸ್ಪತ್ರೆಯ ಹೆಸರು",
            "contact_number" to "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
            "save_changes" to "ಉಳಿಸಿ",
            "full_name" to "ಪೂರ್ಣ ಹೆಸರು",
            "mobile_number" to "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
            "last_donation_date" to "ಕೊನೆಯ ರಕ್ತದಾನ ದಿನಾಂಕ",
            "state" to "ರಾಜ್ಯ",
            "district" to "ಜಿಲ್ಲೆ",
            "city" to "ನಗರ",
            "register_now" to "ಈಗ ನೋಂದಾಯಿಸಿ",
            "request_help" to "ತುರ್ತು ರಕ್ತದ ನೆರವು",
            "emergency_feed_sub" to "ನಿಮ್ಮ ಸಮೀಪದ ಸಕ್ರಿಯ ತುರ್ತು ವಿನಂತಿಗಳು",
            "find_donors_sub" to "ನಿಮ್ಮ ಹತ್ತಿರದ ರಕ್ತದಾನಿಗಳನ್ನು ಹುಡುಕಿ",
            "additional_notes" to "ಹೆಚ್ಚುವರಿ ವಿವರಗಳು",
            "all" to "ಎಲ್ಲಾ",
            "active" to "ಸಕ್ರಿಯ",
            "connected" to "ಸಂಪರ್ಕಿಸಲಾಗಿದೆ",
            "pending" to "ಬಾಕಿ ಇದೆ",
            "available" to "ಲಭ್ಯವಿದೆ",
            "unavailable" to "ಲಭ್ಯವಿಲ್ಲ",
            "select_blood_group" to "ರಕ್ತದ ಗುಂಪನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "select_state" to "ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "select_district" to "ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "select_city" to "ನಗರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "send_request" to "ರಕ್ತದ ವಿನಂತಿ ಕಳುಹಿಸಿ",
            "last_donation" to "ಕೊನೆಯ ದಾನ",
            "post_emergency_submit" to "ತುರ್ತು ವಿನಂತಿ ಸಲ್ಲಿಸಿ ದಾನಿಗಳಿಗೆ ತಿಳಿಸಿ",
            "notification_prefs" to "ಸೂಚನೆ ಆದ್ಯತೆಗಳು",
            "emergency_alerts" to "ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು",
            "eligibility_reminders" to "ಅರ್ಹತಾ ನೆನಪೂಲೆಗಳು",
            "newsletter" to "ಸುದ್ದಿಪತ್ರ & ಸುಳಿವುಗಳು",
            "account_security" to "ಖಾತೆ & ಸುರಕ್ಷತೆ",
            "reset_password" to "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ"
        ),
        "Malayalam (മലയാളം)" to mapOf(
            "home" to "ഹോം",
            "emergencies" to "അടിയന്തിരങ്ങൾ",
            "donors" to "ദാതാക്കൾ",
            "search" to "തിരയുക",
            "my_requests" to "എന്റെ അഭ്യർത്ഥനകൾ",
            "settings" to "ക്രമീകരണങ്ങൾ",
            "profile" to "പ്രൊഫൈൽ",
            "notifications" to "അറിയിപ്പുകൾ",
            "reports" to "റിപ്പോർട്ടുകൾ",
            "search_donors" to "ദാതാക്കളെ തിരയുക",
            "post_emergency" to "അടിയന്തിര അഭ്യർത്ഥന",
            "become_donor" to "രക്തദാതാവാകുക",
            "live_emergencies" to "തത്സമയ അടിയന്തിര അഭ്യർത്ഥനകൾ",
            "view_all" to "എല്ലാം കാണുക",
            "welcome" to "VitalMatch ലേക്ക് സ്വാഗതം",
            "app_theme" to "ആപ്പ് തീം",
            "display_language" to "ഭാഷ",
            "light_mode" to "ലൈറ്റ് മോഡ്",
            "dark_mode" to "ഡാർക്ക് മോഡ്",
            "system_default" to "സിസ്റ്റം",
            "back" to "തിരികെ",
            "call" to "വിളിക്കുക",
            "sms" to "എസ്എംഎസ്",
            "logout" to "ലോഗ് ഔട്ട്",
            "patient_name" to "രോഗിയുടെ പേര്",
            "blood_type" to "ആവശ്യമുള്ള രക്തഗ്രൂപ്പ്",
            "hospital_name" to "ആശുപത്രി പേര്",
            "contact_number" to "ബന്ധപ്പെടേണ്ട നമ്പർ",
            "save_changes" to "സംരക്ഷിക്കുക",
            "full_name" to "പൂർണ്ണ നാമം",
            "mobile_number" to "മൊബൈൽ നമ്പർ",
            "last_donation_date" to "അവസാന രക്തദാന തീയതി",
            "state" to "സംസ്ഥാനം",
            "district" to "ജില്ല",
            "city" to "നഗരം",
            "register_now" to "ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക",
            "request_help" to "അടിയന്തിര രക്ത സഹായ അഭ്യർത്ഥന",
            "emergency_feed_sub" to "നിങ്ങളുടെ അടുത്തുള്ള തത്സമയ അഭ്യർത്ഥനകൾ",
            "find_donors_sub" to "നിങ്ങളുടെ അടുത്തുള്ള രക്തദാതാക്കളെ കണ്ടെത്തുക",
            "additional_notes" to "കൂടുതൽ വിവരങ്ങൾ",
            "all" to "എല്ലാം",
            "active" to "സജീവം",
            "connected" to "ബന്ധിപ്പിച്ചു",
            "pending" to "തീർപ്പുകൽപ്പിക്കാത്തത്",
            "available" to "ലഭ്യമാണ്",
            "unavailable" to "ലഭ്യമല്ല",
            "select_blood_group" to "രക്തഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക",
            "select_state" to "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
            "select_district" to "ജില്ല തിരഞ്ഞെടുക്കുക",
            "select_city" to "നഗരം തിരഞ്ഞെടുക്കുക",
            "send_request" to "രക്ത അഭ്യർത്ഥന അയയ്ക്കുക",
            "last_donation" to "അവസാന ദാനം",
            "post_emergency_submit" to "അടിയന്തിര അഭ്യർത്ഥന സമർപ്പിച്ച് ദാതാക്കളെ അറിയിക്കുക",
            "notification_prefs" to "അറിയിപ്പ് മുൻഗണനകൾ",
            "emergency_alerts" to "അടിയന്തിര അലേർട്ടുകൾ",
            "eligibility_reminders" to "യോഗ്യതാ ഓർമ്മപ്പെടുത്തലുകൾ",
            "newsletter" to "വാർത്താപത്രിക & നുറുങ്ങുകൾ",
            "account_security" to "അക്കൗണ്ട് & സുരക്ഷ",
            "reset_password" to "പാസ്‌വേഡ് മാറ്റുക"
        ),
        "Bengali (বাংলা)" to mapOf(
            "home" to "হোম",
            "emergencies" to "জরুরি",
            "donors" to "দাতা",
            "search" to "খুঁজুন",
            "my_requests" to "আমার অনুরোধ",
            "settings" to "সেটিংস",
            "profile" to "প্রোফাইল",
            "notifications" to "বিজ্ঞপ্তি",
            "reports" to "রিপোর্ট",
            "search_donors" to "দাতা খুঁজুন",
            "post_emergency" to "জরুরি পোস্ট করুন",
            "become_donor" to "দাতা হন",
            "live_emergencies" to "লাইভ জরুরি অনুরোধ",
            "view_all" to "সব দেখুন",
            "welcome" to "VitalMatch-এ স্বাগতম",
            "app_theme" to "অ্যাপ থিম",
            "display_language" to "ভাষা",
            "light_mode" to "লাইট মোড",
            "dark_mode" to "ডার্ক মোড",
            "system_default" to "সিস্টেম",
            "back" to "ফিরে যান",
            "call" to "কল করুন",
            "sms" to "এসএমএস",
            "logout" to "লগআউট",
            "patient_name" to "রোগীর নাম",
            "blood_type" to "প্রয়োজনীয় রক্তের গ্রুপ",
            "hospital_name" to "হাসপাতালের নাম",
            "contact_number" to "যোগাযোগের নম্বর",
            "save_changes" to "সংরক্ষণ করুন",
            "full_name" to "পুরো নাম",
            "mobile_number" to "মোবাইল নম্বর",
            "last_donation_date" to "শেষ রক্তদানের তারিখ",
            "state" to "রাজ্য",
            "district" to "জেলা",
            "city" to "শহর",
            "register_now" to "এখনই নিবন্ধন করুন",
            "request_help" to "জরুরি রক্তের সাহায্য অনুরোধ",
            "emergency_feed_sub" to "আপনার কাছাকাছি লাইভ অনুরোধ",
            "find_donors_sub" to "আপনার কাছাকাছি রক্তদাতা খুঁজুন",
            "additional_notes" to "অতিরিক্ত বিবরণ",
            "all" to "সব",
            "active" to "সক্রিয়",
            "connected" to "সংযুক্ত",
            "pending" to "পেন্ডিং",
            "available" to "উপলব্ধ",
            "unavailable" to "অনুপলব্ধ",
            "select_blood_group" to "রক্তের গ্রুপ নির্বাচন করুন",
            "select_state" to "রাজ্য নির্বাচন করুন",
            "select_district" to "জেলা নির্বাচন করুন",
            "select_city" to "শহর নির্বাচন করুন",
            "send_request" to "রক্তের অনুরোধ পাঠান",
            "last_donation" to "শেষ দান",
            "post_emergency_submit" to "জরুরি পোস্ট করুন ও দাতা জানান",
            "notification_prefs" to "বিজ্ঞপ্তি পছন্দসমূহ",
            "emergency_alerts" to "জরুরি সতর্কতা",
            "eligibility_reminders" to "যোগ্যতা অনুস্মারক",
            "newsletter" to "নিউজলেটার ও টিপস",
            "account_security" to "অ্যাকাউন্ট ও নিরাপত্তা",
            "reset_password" to "পাসওয়ার্ড রিসেট করুন"
        ),
        "Marathi (मराठी)" to mapOf(
            "home" to "होम",
            "emergencies" to "आणीबाणी",
            "donors" to "रक्तदाते",
            "search" to "शोधा",
            "my_requests" to "माझ्या विनंत्या",
            "settings" to "सेटिंग्ज",
            "profile" to "प्रोफाइल",
            "notifications" to "सूचना",
            "reports" to "अहवाल",
            "search_donors" to "रक्तदाते शोधा",
            "post_emergency" to "आणीबाणी विनंती करा",
            "become_donor" to "रक्तदाते बना",
            "live_emergencies" to "थेट आणीबाणी विनंत्या",
            "view_all" to "सर्व पहा",
            "welcome" to "VitalMatch मध्ये स्वागत",
            "app_theme" to "ॲप थीम",
            "display_language" to "भाषा",
            "light_mode" to "लाइट मोड",
            "dark_mode" to "डार्क मोड",
            "system_default" to "सिस्टम",
            "back" to "मागे",
            "call" to "कॉल करा",
            "sms" to "एसएमएस",
            "logout" to "लॉगआउट",
            "patient_name" to "रुग्णाचे नाव",
            "blood_type" to "आवश्यक रक्त गट",
            "hospital_name" to "रुग्णालयाचे नाव",
            "contact_number" to "संपर्क क्रमांक",
            "save_changes" to "जतन करा",
            "full_name" to "पूर्ण नाव",
            "mobile_number" to "मोबाईल क्रमांक",
            "last_donation_date" to "शेवटची रक्तदान तारीख",
            "state" to "राज्य",
            "district" to "जिल्हा",
            "city" to "शहर",
            "register_now" to "आता नोंदणी करा",
            "request_help" to "तातडीच्या रक्त मदतीची विनंती",
            "emergency_feed_sub" to "तुमच्या जवळील थेट विनंत्या",
            "find_donors_sub" to "तुमच्या जवळचे रक्तदाते शोधा",
            "additional_notes" to "अतिरिक्त तपशील",
            "all" to "सर्व",
            "active" to "सक्रिय",
            "connected" to "जोडले गेले",
            "pending" to "प्रलंबित",
            "available" to "उपलब्ध",
            "unavailable" to "अनुपलब्ध",
            "select_blood_group" to "रक्त गट निवडा",
            "select_state" to "राज्य निवडा",
            "select_district" to "जिल्हा निवडा",
            "select_city" to "शहर निवडा",
            "send_request" to "रक्त विनंती पाठवा",
            "last_donation" to "शेवटचे रक्तदान",
            "post_emergency_submit" to "आणीबाणी नोंदवा आणि रक्तदात्यांना कळवा",
            "notification_prefs" to "सूचना प्राधान्ये",
            "emergency_alerts" to "आणीबाणी इशारे",
            "eligibility_reminders" to "पात्रता आठवणी",
            "newsletter" to "न्यूजलेटर आणि टिप्स",
            "account_security" to "खाते आणि सुरक्षा",
            "reset_password" to "पासवर्ड बदला"
        ),
        "Gujarati (ગુજરાતી)" to mapOf(
            "home" to "હોમ",
            "emergencies" to "ઇમરજન્સી",
            "donors" to "દાતા",
            "search" to "શોધો",
            "my_requests" to "મારી વિનંતીઓ",
            "settings" to "સેટિંગ્સ",
            "profile" to "પ્રોફાઇલ",
            "notifications" to "સૂચનાઓ",
            "reports" to "રિપોર્ટ્સ",
            "search_donors" to "દાતા શોધો",
            "post_emergency" to "ઇમરજન્સી પોસ્ટ કરો",
            "become_donor" to "દાતા બનો",
            "live_emergencies" to "લાઈવ ઇમરજન્સી વિનંતીઓ",
            "view_all" to "બધું જુઓ",
            "welcome" to "VitalMatch માં આપનું સ્વાગત છે",
            "app_theme" to "એપ થીમ",
            "display_language" to "ભાષા",
            "light_mode" to "લાઇટ મોડ",
            "dark_mode" to "ડાર્ક મોડ",
            "system_default" to "સિસ્ટમ",
            "back" to "પાછા",
            "call" to "કોલ કરો",
            "sms" to "એસએમએસ",
            "logout" to "લોગઆઉટ",
            "patient_name" to "દર્દીનું નામ",
            "blood_type" to "જરૂરી બ્લડ ગ્રુપ",
            "hospital_name" to "હોસ્પિટલનું નામ",
            "contact_number" to "સંપર્ક નંબર",
            "save_changes" to "સાચવો",
            "full_name" to "પૂરૂ નામ",
            "mobile_number" to "મોબાઇલ નંબર",
            "last_donation_date" to "છેલ્લી રક્તદાન તારીખ",
            "state" to "રાજ્ય",
            "district" to "જિલ્લો",
            "city" to "શહેર",
            "register_now" to "હમણાં નોંધણી કરો",
            "request_help" to "તાત્કાલિક બ્લડ મદદ વિનંતી",
            "emergency_feed_sub" to "તમારી નજીકની લાઈવ વિનંતીઓ",
            "find_donors_sub" to "તમારી નજીકના રક્તદાતાઓને શોધો",
            "additional_notes" to "વધારાની વિગતો",
            "all" to "બધા",
            "active" to "સક્રિય",
            "connected" to "જોડાયેલ",
            "pending" to "પેન્ડિંગ",
            "available" to "ઉપલબ્ધ",
            "unavailable" to "અનઉપલબ્ધ",
            "select_blood_group" to "બ્લડ ગ્રુપ પસંદ કરો",
            "select_state" to "રાજ્ય પસંદ કરો",
            "select_district" to "જિલ્લો પસંદ કરો",
            "select_city" to "શહેર પસંદ કરો",
            "send_request" to "બ્લડ વિનંતી મોકલો",
            "last_donation" to "છેલ્લું દાન",
            "post_emergency_submit" to "ઇમરજન્સી પોસ્ટ કરો અને દાતાઓને જાણ કરો",
            "notification_prefs" to "સૂચના પસંદગીઓ",
            "emergency_alerts" to "ઇમરજન્સી અલર્ટ્સ",
            "eligibility_reminders" to "પાત્રતા રીમાઇન્ડર્સ",
            "newsletter" to "ન્યૂઝલેટર & ટિપ્સ",
            "account_security" to "ખાતું & સુરક્ષા",
            "reset_password" to "પાસવર્ડ બદલો"
        )
    )

    fun get(key: String): String {
        val currentLang = ThemeState.languageMode.value
        val langMap = translations[currentLang] ?: translations["English"]!!
        return langMap[key] ?: translations["English"]!![key] ?: key
    }
}
